#! python

from rivtlib.rvreport import *  # noqa: F403

""" generate rivt report

Sample report generating and config file. The report generating file must
located in rivtdocs/reports/. The report output file is written to the same
folder. Duplicate report file names are incremented, not overwritten. 

Run this Python file to generate a rivt report. Copy and rename the file to
save custom report settings. 

A flag determines whether the report is assembled from existing doc files or
whether docs are regenerated prior to assembly. (see "report type and paths"
below). If a rivt or doc file is specified for inclusion and not found a
warning is given but the report is still assembled.

A rivt report organizes rivt folders into divisions, and rivt doc files as
subdivisions. rivt doc numbers define this structure. Default titles for
subdivisions and divisions are generated by stripping the doc or div number
from the file or folder name and replacing underscores with spaces. The default
titles may be overridden (see "optional rename" below). 
"""

# ==================================
# report type
# ==================================
rpttypeS = "pdf"  # report type [html; pdf; texpdf; text]
rvrunB = False  # regenerate docs [True; False]

# ==================================
# report and division settings
# ==================================
# rptcover = "cover.pdf"
# generate a report cover
rpttitleS = "Solar Canopy Calculations"
rptsubtitleS = "Larkspur, Ca"
rptauthorS = "rhh"
rptdateS = "<datetime>"
rptcoverS = "cover1.pdf"  # cover page [name.rst; name.pdf], "" to omit
# division labels used in toc
rpttocB = True  # add table of contents
dv1S = "Codes and Loads"
dv2S = "Materials"
dv3S = "Foundation"

# include docs in report
rptL = [
    "rv101",
    "rv102",
    "rv201",
    "rv202",
    "rv301",
    "rv302",
]
genreport()  # noqa: F405
